### ISSUE TITLE
Request: please update papermc hangar listing

### ISSUE THREAD

**Issue by ConnorBP** [jensjeflensje/minecraft_imagery#10]
this is currently out of date, and it isn't very clear how to get to the latest version here on github from there. The only link to this repo is a broken readme url.

https://hangar.papermc.io/jensjeflensje/ImageryAPI

was probably forgotten about so I'll just throw a reminder in here

**Comment by jensjeflensje** [comment]
You're right. I totally forgot I even had this entry. Thanks for letting me know, it's updated now.
