### ISSUE TITLE
missing block fix

### ISSUE THREAD

**Issue by kuraiskrap** [jensjeflensje/minecraft_imagery#6]
i noticed that not all blocks are in the config yet, i might submit missing blocks as i find them
would it be possible to have a block missing in the config simply using the default map colors for that block?

this is the skript version of the code that grabs the map color data that i used to add to the config (submitted a pull request)

import:
	org.bukkit.Color

command /debuggetcolor:
	trigger:
		set {_rgb} to (block data of target block of player).getMapColor()
		set {_r} to {_rgb}.getRed()
		set {_g} to {_rgb}.getGreen()
		set {_b} to {_rgb}.getBlue()
		broadcast "%raw name of target block of player%: %{_r}%,%{_g}%,%{_b}%"
		
output example: "minecraft:spruce_log: 129,86,49"

i think i saw this was Async somewhere, not sure if bukkit calls would be a issue for that

**Comment by jensjeflensje** [comment]
This would be a good addition, but please keep in mind that the `getMapColor` method has only been introduced in Minecraft version 1.20.4. I would like to support more versions (1.16 to 1.21 in an ideal scenario), so it would need to be added to the compatibility patches.

**Comment by kuraiskrap** [comment]
That's fair
I've run into my own compatibility issues with my skript projects

I wish I could code Java and pitch in
I have no idea how you managed to do this async

**Comment by jensjeflensje** [comment]
I actually made a pull request already in which I added this fix. You can see it attached to this issue. I just need to test it.

If it works, I can create a new release that includes it :)
